name: Update README

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'

    - name: Install Dependencies
      run: |
        gem install octokit dotenv

    - name: Run Update Script
      run: |
        ruby scripts/update_readme.rb
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        USERNAME: ${{ secrets.USERNAME }}

    - name: Commit and Push Changes with GPG
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.signingkey 04FC999439741F58
        git config --global commit.gpgsign true
        git add .
        git commit -S -m "Update README with recent activity"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
